name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker-compose build
        
    - name: Start services
      run: |
        docker-compose up -d
        
    - name: Wait for app to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'
        
    - name: Test API endpoints
      run: |
        curl -f http://localhost:3000/api/devices
        curl -f http://localhost:3000
        
    - name: Show logs
      if: always()
      run: |
        docker-compose logs
        
    - name: Stop services
      if: always()
      run: |
        docker-compose down -v
